Support for ArduinoJson version 6
SignalK/SensESP pull request #172
Opened 2020-09-25 18:08 UTC by JohnySeven

Hi Guys!

I've started where @ba58smith ended and finished it. Have working ESP8266 device that is able to connect to SK server, send deltas, store and load configuration from SPIFFS and everything looks in working state.

Please review my changes and let's discuss them.

Thanks,
Jan

2020-09-25 19:08 UTC, mairas requested changes
OK, that's been one hell of an ordeal! Well done!

I've got only a couple of minimal comments. Also, given the extent of this work, I'd also like to kick the tires a bit. I'm doing yacht club guard duty tonight (meh...) and didn't take any of the devices with me, so that'll be only tomorrow, at earliest.

2020-09-25 20:16 UTC, ba58smith commented
Nice work, @JohnySeven . Funny that you gave me some credit - I think you had to change everything I did! 

I'm travelling, but have my computer, ESP's, and SK Server Pi with me, so I'll try to give it all a good workout ASAP.

2020-09-26 14:24 UTC, ba58smith commented on src/net/http.cpp
> +            //if (body.success()) {
From https://arduinojson.org/v6/doc/upgrade/: "With ArduinoJson 5, JsonVariant had value semantic. It was possible to create a instance without a JsonBuffer. With ArduinoJson 6, JsonVariant has reference semantics, like JsonArray and JsonObject. You need a JsonDocument to initialize a JsonVariant." 

Does that mean we need a JsonDocument somewhere to initialize the JsonVariant, before we can do anything else with the JsonVariant? Right now, the first reference to the `json` variable is this: `JsonObject body = json.as<JsonObject>();`. Is that OK?

2020-09-26 15:02 UTC, JohnySeven commented on src/net/http.cpp
> +            //if (body.success()) {
@mairas I agree, also check out this https://github.com/me-no-dev/ESPAsyncWebServer/blob/f13685ee97675be2ac9502d177d3024ebc49c1e0/src/AsyncJson.h#L224 - there is parsing error checking and if parsing fails it will not call SensESP handler, but to be sure, I'll add NULL check as requested.
@ba58smith The variant is created in ESPAsyncWebService library, here: https://github.com/me-no-dev/ESPAsyncWebServer/blob/f13685ee97675be2ac9502d177d3024ebc49c1e0/src/AsyncJson.h#L225
I think it's just fine as it is.

2020-09-26 15:04 UTC, JohnySeven commented on src/net/ws_client.cpp
>    JsonObject resp = doc.as<JsonObject>();
Yes, nice catch! 👍

2020-09-26 15:07 UTC, JohnySeven commented
Thanks @ba58smith. I had to give some credit as you started it 👍 

What I've not tested is subscription to SK values - there is JSON serialization involved and this is something I've not tested yet.

2020-09-26 19:14 UTC, ba58smith commented on src/net/http.cpp
> +            //if (body.success()) {
Ah, I see - deserializeJson() is checked for an error before `json` ever appears in http.cpp. Thanks for the explanation.

2020-09-27 09:18 UTC, mairas commented on src/net/http.cpp
> +            //if (body.success()) {
@JohnySeven good point re `AsyncJson.h` error checking. It'd be unnecessary to check it twice (esp. because going from JsonVariant to JsonObject is likely to be just a cast).

2020-09-27 09:20 UTC, mairas commented on src/net/http.cpp
> +            //if (body.success()) {
@ba58smith we're getting a reference to an already created JsonVariant, so the necessary object creation has already happened behind the scenes. Is that what you asked?

2020-09-27 12:44 UTC, ba58smith commented on src/net/http.cpp
> +            //if (body.success()) {
@mairas - Yes, that was my question. I didn't dig deep enough (into ESPAsyncWebService) to see that it's already being done prior to `json` appearing in http.cpp.

2020-09-28 19:18 UTC, JohnySeven commented on src/net/http.cpp
> +            //if (body.success()) {
Np :-) I've removed the commented out code.

2020-09-28 19:20 UTC, JohnySeven commented
OK, I suppose everything is ready for merge. So it's up to you guys now! :-)

2020-09-29 07:02 UTC, mairas commented
Thanks a lot! Merging.

2020-09-29 07:02 UTC, merged