Smart switches
SignalK/SensESP pull request #261
Opened 2020-11-19 22:52 UTC by joelkoz

This PR builds on the SKPutRequestListener enhancement, and adds a "Smart switch" to the sensors list.  SmartSwitches are relay controlled loads that can be manually set by the user pressing a physical button, as well as set programmatically via PUT requests to set the state.

In addition to the Button and SmartSwitch sensor types, new transforms are added to help translate physical button presses into "Click types" to identify things like a "long click" and a "double click."

Start with the examples/smart_switch.cpp file and work from there when reviewing the PR.

I'm not sure if this is starting to strain the limits of what should be in the SensESP framework vs. what should be in more application/implementation specific repos. I tend to think there is interest in this type of device, so having it in the core framework may prove useful to other users.

2020-11-20 15:33 UTC, ba58smith commented
You'll need to figure out why the checks (which try to compile all of the examples with  your new code) didn't pass.

2020-11-20 20:18 UTC, joelkoz commented
Correct. The other PR is the SKPutRequestListener. I am certain we will want that one in the core framework. This switches build requires that PR, but I wanted to discuss whether or not this PR was too application specific or not, so I kept it separate.

I think it is valuable and there seems to be some interest in it, but I wanted your guys opinion since its been a while since I’ve been involved and I feel a bit out of the loop. 

> On Nov 20, 2020, at 10:32 AM, Brian Smith <notifications@github.com> wrote:
> 
> ﻿
> You've got a commit in this PR from your other PR.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-20 21:55 UTC, ba58smith reviewed
RE: this possibly straining the limits of what should be in the SensESP framework, maybe we need to know how much bigger it makes the binary to simply be in the framework, vs. being used in a main.cpp. It's certainly going to have a lot of uses, so if it doesn't make EVERY binary bigger by very much, then I'd say include it. If it's going to make every project bigger by a significant amount, then it should probably be in another repo, and used only when a project needs it.

2020-11-20 21:55 UTC, ba58smith commented on src/transforms/repeat_report.h
> +  }
Why define the constructor here in the .h file, rather than in the .cpp file, as is typically done? (Asking for a friend, who doesn't understand why we do it one way sometimes, and the other way other times.)

2020-11-20 21:55 UTC, ba58smith commented on src/transforms/repeat_report.cpp
> +}
Woud it be more efficient to do this with `app.onDelay(maxSilenceInterval, [this] etc....`?

2020-11-20 21:55 UTC, ba58smith commented on src/transforms/repeat_report.h
> +  long maxSilenceInterval;
Not using camel case for anything other than class names anymore. (For the most part - see https://github.com/SignalK/SensESP/pull/182/files)

2020-11-20 21:55 UTC, ba58smith commented on src/transforms/truth_text.h
> +extern bool textIsTrue(String value);
Lots of camel case variables in this file and the related .cpp. (See https://github.com/SignalK/SensESP/pull/182/files)

2020-11-20 21:55 UTC, ba58smith commented on src/transforms/truth_text.h
> +    TruthToText(const char* trueValue="ON", const char* falseValue="OFF") {
Formatting: spaces around `=`.

2020-11-20 21:55 UTC, ba58smith commented on src/transforms/truth_text.cpp
> +
To be thorough, should you also have `if (input.toInt() == 0)`?

2020-11-20 21:55 UTC, ba58smith commented on src/sensors/smart_switch_controller.cpp
> +        this->emit(true);
Should this be `this->emit(false)`?

2020-11-20 22:13 UTC, ba58smith commented on examples/smart_switch.cpp
> +     ->connect_to(controller);
Since the button is the input to the controller, and the SmartSwitch is the output from the controller, would it be easier to understand if you put the Button code before the SmartSwitch code?

2020-11-20 23:10 UTC, ba58smith commented
> Correct. The other PR is the SKPutRequestListener. I am certain we will want that one in the core framework. This switches build requires that PR, but I wanted to discuss whether or not this PR was too application specific or not, so I kept it separate. I think it is valuable and there seems to be some interest in it, but I wanted your guys opinion since its been a while since I’ve been involved and I feel a bit out of the loop.
> […](#)

Sorry, that wasn't my point. My point was you have done two commits, one for each of two PR's. But both of the commits are in this PR. You need to remove the commit from this PR that doesn't belong with this PR. (We've had a whole bunch of problems with PR's having commits that don't belong to them lately.)

2020-11-21 19:17 UTC, joelkoz commented on examples/smart_switch.cpp
> +     ->connect_to(controller);
Sure, I can do that. I think the current order is an artifact from some testing I was doing as I was having a problem making a single long connect_to() chain.

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/click_type.h
> +      ClickType(String config_path, int long_click_delay=1300, int double_click_interval=350, int ultra_long_click_delay=5000);
You are correct.  The comment actually belongs to the enum definition of ClickTypes. It was briefly a member of the ClickType class vs. a global enumeration.  I had some trouble getting things to compile correctly that way, so I punted.

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/click_type.h
> +      DelayReaction* pQueuedReport;
Ah yes.  I did notice that, and have tried to follow it in general,  Old habits die hard - I've been using camel case and Hungarian notation for 35 years!  At least you guys kept the curly brackets in the correct place! :P

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/repeat_report.cpp
> +}
Actually no.  The problem with onDelay is that is harder to modify once it's been queued.  If you look closely at the code, the last_update value is constantly resetting.  The delay we are looking for is maxSilenceInterval since the last time an update came in, not since we last executed the onDelay() call.  The alternative implementation would be to keep a pointer to the onDelay response object, and when a new press comes in, execute a "remove" on the old response object, then set up a new one.  The current implementation is actually simpler in the long run IMO

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/repeat_report.h
> +  }
So, when you use inline statements (whether they be in a template or not), the compiler generates the code "inline" every time its referenced.  That is, if there are 10 calls to `set_input()`, and `set_input()` is defined inline, the compiler will generate the implementation of code 10 times, each being right at the point of use (vs. one time, and then use 10 "jump to subroutine" instructions).  For complicated code, this can cause a lot of code bloat.  That is why, most of the time, we put the code in the .cpp file.  The best use of the "inline" implementation is for very simple implementations (like assign a value to a variable).  Those end up being not much larger object code wise than the "jump to subroutine" instructions.

Things get a little more complicated when it comes to templates, however.  Without the implementation code, the compiler does not know how to generate code for an arbitrary type that you may make up in the future.  If you want the template to be usable with any and all types, you HAVE to put code inline.  You HAVE to accept the code bloat.  The compromise is to put the implementation in the .cpp file, and then add references like this (as found at the end of repeat_report.cpp):
```
// Force compiler to make versions for the common data types...
template class RepeatReport<float>;
template class RepeatReport<int>;
template class RepeatReport<bool>;
template class RepeatReport<String>;
```

What that does is generates the code for those data types, so the linker can find and use them.  The downside is, if we were to use `RepeatReport<ClickType>` or any other type not in that list, we'd get a linker error, as the implementation code would not exist anywhere.

As to why the constructor code is inline and not the other: There were some syntax issues with putting it in the .cpp file that I was struggling with, so again, I punted.  The constructor doesn't really do too much. It is the configuration code that is larger, and could get bloated if repeat_report will used in multiple places.

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/repeat_report.h
> +  long maxSilenceInterval;
old dog here... :)

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/truth_text.cpp
> +
No.  Any sequence of numbers will return a non-zero value, but you will get "zero" back from `toInt()` for both "0" as well as  "_abc_".   "_abc_" is not a valid version of TRUE, but it's not a valid version of FALSE either.  Perhaps I will rename these methods `is_valid_true()` and `is_valid_false()` instead.  That makes their true intention more clear.  All of this is used in the smart switch controller to say "if a valid true string, turn on; if a valid false string, turn off; otherwise, toggle state"

2020-11-21 20:56 UTC, joelkoz commented on src/transforms/truth_text.h
> +extern bool textIsTrue(String value);
yeah, yeah, yeah :P :)

2020-11-21 22:49 UTC, joelkoz commented
> Sorry, that wasn't my point. My point was you have done two commits, one for each of two PR's. But both of the commits are in this PR. You need to remove the commit from this PR that doesn't belong with this PR. (We've had a whole bunch of problems with PR's having commits that don't belong to them lately.)

This PR is a superset of the other. If we decided to do ONLY the SKPutRequestListener, we'd just delete this PR. If we decide to take it all (which right now I think we should), we just delete or ignore the other PR.

2020-11-21 22:53 UTC, joelkoz commented
> You'll need to figure out why the checks (which try to compile all of the examples with your new code) didn't pass.

There were some warnings that I ignore on my machine that apparently are considered errors by  the automated build.  I corrected them in the source, and now it compiles ok for ESP8266, but does not for ESP32 as the analogWrite() method that I use to control the color LED is not implemented in ESP32.  I am going to tweeze out that code, and then make an ESP32 compatible version.

2020-11-21 22:54 UTC, joelkoz commented on src/sensors/button.cpp
> +     bool nowPushed = (state == HIGH);
The state to use for "pressed" is now an optional parameter.

2020-11-21 23:39 UTC, ba58smith commented on src/sensors/button.h
> + */
Much better. 

"Until" has only one "l".

2020-11-21 23:42 UTC, ba58smith commented on src/transforms/truth_text.cpp
> +
Got it. I didn't know that's how `toInt()` behaved. Rename them if you like, but it's probably not necessary. I just thought you omitted a specific case, which you did not.

2020-11-23 12:08 UTC, mairas requested changes
In the future, please split pull requests into smaller entities. This PR had lots of good and interesting stuff but was really frustrating to review due to its size and a lot of totally unrelated pieces of code.

2020-11-23 12:08 UTC, mairas commented on src/transforms/truth_text.cpp
> +     this->emit(is_valid_true(input));
Should the cast to OUT be explicit?

2020-11-23 12:08 UTC, mairas commented on src/transforms/truth_text.cpp
> +     this->emit(is_valid_true(input));
Although, why doesn't TextToTruth always emit a boolean?

2020-11-23 15:18 UTC, joelkoz reviewed
> In the future, please split pull requests into smaller entities. This PR had lots of good and interesting stuff but was really frustrating to review due to its size and a lot of totally unrelated pieces of code.

@mairas Believe it or not, ALL of the classes in this PR are used to implement the smart switch.  There is no unrelated code.  As I was developing it, I found some of my higher level classes would benefit from being broken down into finer grained transforms.  That is why there is a bunch of stuff here.  To get a true feel for how it all fits together, its best to study just the `smart_switch_example.cpp`

2020-11-23 15:18 UTC, joelkoz commented on src/transforms/repeat_report.cpp
> +}
The compromise I think is to keep the code as is, but to change `onTick()` to something like `onDelay(10....)`. That would put a minimum resolution of the repeat intervals at 10 milliseconds, but I think that is probably more than OK for what the repeat_report would be used for.  Certainly in this use, `repeat_report()` is used for repeating on a magnitude of seconds, not milliseconds.  Perhaps I'll do that. That keeps us to 100 times per second, not 100k.

2020-11-23 15:18 UTC, joelkoz commented on src/transforms/truth_text.cpp
> +     this->emit(is_valid_true(input));
Since Signal K in the wild has seen switches controlled using `true`|`false`, `"on"`|`"off"` and `1`|`0`, there is a need for `TextToTruth()` to handle a variety of inputs.  Given that, I just figured the inverse was true.  I suppose those 'non-boolean but numeric' use cases could be handled with transforms if needed.  That would certainly make this code easier to use.

2020-11-23 15:33 UTC, joelkoz commented on src/controllers/smart_switch_controller.cpp
> +    this->emit(!output);
Actually - maybe I am misunderstanding your comment? You are objecting to SmartSwitchController being an Observable? Or, you are objecting to the use of the variable 'output' to store the state.  If I look at the `emit()` implementation of `ValueProducer<>`, it is storing its value in `output`. Are you saying that ValueProducer descendant classes (like the standard transforms) are starting to use their own state variable, and simply passing those to `emit()`? I guess I could do that, but in practice, that is simply doubling the memory used per transform. The `output` variable is declared in the `ValueProducer` template. If a declared a member of `SmartSwitchController` that is something like `bool switch_state`, I would be declaring a second variable of the same type as `output` that would always have the exact same value.  Have you guys determined that for the sake of clarity, that is an inefficiency you are willing to accept?

2020-11-24 00:51 UTC, joelkoz commented
Ok guys, I think I am ready for this first pass.  I've implemented most of the changes asked for.  There are a few "still out there", but I am going to leave them for a later PR.  I'd like to get this one committed so I can start work on SKPutRequest(), which will allow SensESP devices to send PUT requests to the SK server.  That is the official way of having a device "change" another device's state.

As with the other PR, I would start with the examples/smart_switch_controller.cpp to see how an end user would view this.

2020-11-24 00:55 UTC, joelkoz commented on src/sensors/button.cpp
> +  // app.onInterrupt(pin, interrupt_type, [this]() {
I tested again, and the onInterrupt() will NOT work for me.  The implementation as is does work.  Perhaps we can set up a test case and rework later?

2020-11-24 00:58 UTC, joelkoz commented on src/transforms/click_type.h
> +      long press_started;
Document what?  All of those methods are inherited from the base class.  The Doxygen takes the base implementation docs if there is no override.

2020-11-24 06:10 UTC, ba58smith commented
I've now done all the review I'm capable of. You say there are some unresolved comments that you want to hold off on for now, and then address them in a later PR. If @mairas approves of that approach, I would simply ask that you create an Issue to keep track of anything that still should be done in a later PR>

2020-11-24 14:24 UTC, mairas commented on src/controllers/smart_switch_controller.cpp
> +    this->emit(!output);
Yes, I was only complaining about using the `output` variable. I think its existence is a bit of an implementation detail and like you said, it's better to use `emit()` to spit the values out of ValueProducers. It may add the overhead of one more output type variable, but only for transforms maintaining some state but for the sake of clarity, I think it's well worth it. That's at least what I've been doing in my new code and in any PR reviews lately.

2020-11-24 14:27 UTC, mairas commented on src/controllers/smart_switch_controller.cpp
> +        this->emit(!output);
I guess my argument was that "the right thing" might not be to toggle the output but this really is no biggie, I don't mind it staying as it is.

2020-11-24 14:29 UTC, mairas commented on src/sensors/button.cpp
> +  // app.onInterrupt(pin, interrupt_type, [this]() {
Yep, sure. I believe Butch has had some problems with it as well, so I guess I have to accept the current implementation doesn't work. :-D

2020-11-24 14:31 UTC, ba58smith approved these changes

2020-11-24 15:04 UTC, mairas commented on src/sensors/button.h
> + * However, if the button is pressed and held longer than repeat_start_interval
Having containing classes is fine, IMO. Another approach is to use helper functions to set up more complex structures as in `wiring_helpers.*` (although all of them probably should be considered deprecated).

If you go that way, could you rename the repeating input thing something else than "Button", though? A DigitalInput that does repeating is no more button-ey than just a DigitalInput itself. However, a DigitalInput coupled with the ClickTypes transform _does_ have button-like properties, IMO.

2020-11-24 15:05 UTC, mairas commented on src/system/led_light.cpp
> +int8_t channel_to_pin[16] = { -1, -1, -1, -1,
Could you add comments in the code describing what's going on here? And remove the global array.

2020-11-24 15:19 UTC, mairas commented on src/system/led_light.cpp
> +static void analogWrite(uint8_t pin, uint32_t value, uint32_t valueMax = 255)
I can't say I'm excited about that approach - it's somewhat unobvious to an unsuspecting reader. If you insist on it, please add a comment about that above `analogWrite`.

2020-11-24 15:34 UTC, mairas commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
But Button was just pretty much a DigitalInput that repeats. ClickType is the entity that transforms the raw input into semantic UI events, and I think button press/release events are different from the physical inputs. For example, with the ClickTypes you don't have to considered whether the input is active-low or active-high and you shouldn't need to care about debouncing.

2020-11-24 15:35 UTC, mairas commented on src/transforms/click_type.h
> +      long press_started;
All the delays and intervals below. Reading the logic is difficult without knowing the exact purpose of each variable.

2020-11-24 16:10 UTC, joelkoz commented on src/controllers/smart_switch_controller.h
> + * The incoming boolean values, on the other hand, are assumed to be
Ah I see.  I will rework the comment using your descriptions, as yes, it is accurate.  As far as click types, ANY of the click type values will toggle the output, which the exception of UltraLongSingleClick, which will reset the MCU.

2020-11-24 16:15 UTC, joelkoz commented on src/sensors/button.h
> + * However, if the button is pressed and held longer than repeat_start_interval
I'm taking this idea and opening up a separate issue to be address is a separate PR.

2020-11-24 16:20 UTC, joelkoz commented on src/system/led_light.h
> +#define _led_color_H_
Yes!  Good catch. I missed that when I refactored

2020-11-24 16:27 UTC, joelkoz commented on src/system/led_light.h
> +       int led_b_pin;
As a matter of habit, I try not to use `private` unless I am 100% certain I want to hide the details and prevent a future developer from making a descendent class.  I don't like to assume that I know that a future developer has no use for descendent classes.  It's similar to the reason I never declare virtual methods `final`. It just artificially limits things.

2020-11-24 16:36 UTC, joelkoz commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
Correct.  But, if you are interested in getting press/release events, you can wire directly from the `Button` (or the debounce) and bypass the `ClickType`.  I suppose I could add them as events in `ClickType` also, but that would complicate and already complicated implementation.  For example, when `ClickType` receives the press release, it needs to wait to see if we are dealing with a single click or a double click.  You can't release the `press release` event until you know if its a press release of a single click or a double click.  You have to wait for the second click.  If the second click never comes, only then can you release the press UP, but at that time, you are already releasing the "SingleClick" event.  That is, unless you are only interested in the event "press release", and not "SingleClickRelease" or "DoubleClickRelease"
  I think I'd like to defer this for a refactor for when we have an actual use case so I can get clarity on exactly what type of events are useful.

2020-11-24 16:37 UTC, joelkoz commented on src/transforms/click_type.h
> +      long press_started;
Ah. Ok, now I understand.

2020-11-24 17:53 UTC, merged

2020-11-24 17:57 UTC, joelkoz commented on library.json
> +      "version": "6.9.0"
Dropping breadcrumbs - the response indicated that EspSoftwareSerial should not be included as an explicit dependency unless you are building for ESP32. That class is already included in the ESP8266 code tree.