Button and ClickType
SignalK/SensESP pull request #272
Opened 2020-11-24 19:31 UTC by joelkoz

Classes for handling button presses

2020-11-24 21:51 UTC, mairas requested changes

2020-11-24 21:51 UTC, mairas commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
As discussed, `Button` is too broad (and misleading) a name for DigitalInput that merely repeats its output.

2020-11-24 21:51 UTC, mairas commented on src/transforms/click_type.cpp
> +  if (input) {
As mentioned before, this needs reimplementing. Logic is convoluted, state is maintained (I think) in multiple variables that are not described, etc. I believe this could be cleanly expressed by a state machine, for example.

2020-11-24 21:51 UTC, mairas commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
As mentioned before, I think ButtonPress and ButtonRelease are also semantically UI events that could (and should) be reported because UI actions could also be based on them.

2020-11-24 22:45 UTC, joelkoz commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
For clarification - you are interested in ButtonPress and ButtonRelease only, and not those differentiated for both single AND double clicks, right?  You expect to see:

```
ButtonPress -> ButtonRelease -> <short pause> ButtonPress -> ButtonRelease-> DoubleClick
```

and not

```
ButtonPress -> ButtonRelease -> <short pause> DoubleButtonPress-> DoubleButtonRelease-> DoubleClick
```

How about a compromise, and I add a boolean to the constructor that specifies if those should be sent?  Certainly, for my current use, having to deal with those actually complicates the implementation of SmartSwitchController, as now it will have to watch for those and throw them out.  SmartSwitchController is only interested in UltraLongButtonClick, and everything else. A single click and a double click both represent a simple single action (toggle the light), not five.

2020-11-24 22:50 UTC, ba58smith commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
So you want a single click and a double click to do the exact same thing in the SmartSwitchController: toggle the switch? Why not a triple click, too? :-)
This seems strange to me, and unnecessary. If it's documented that a single click will toggle the status, that's what people will expect.

2020-11-24 22:52 UTC, ba58smith commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
And I've been meaning to ask: what's the purpose of repeating the output every so often? What's the use case?

2020-11-24 22:54 UTC, joelkoz commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
`PressRepeater`?

That only makes sense if the digital input functionality is removed entirely.  Perhaps `Button` is a candidate for one of those high level "composite classes" that wires itself to make it easier for the end user to use

2020-11-24 22:58 UTC, joelkoz commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
Its not that I WANT a double click to do it. It's that I don't care.  I think it would be confusing to an end end user (that is, the user of a device created by one of our users) that if they double click on the light switch, it would do NOTHING.  I know that would confuse my wife!  We have automated dimmers all over the house that response to clicks and double clicks.

If its documented that a single click will toggle, and they never try a double click, then no harm no foul.  What behavior would you expect?  A quick on/off?

One could always go into the configuration and make the "DoubleClickInterval" so long that the ClickType transform would never register a double click.

2020-11-24 23:06 UTC, joelkoz commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
@ba58smith Think of the "volume up" button on a remote control.  To raise or lower the volume, users usually just presses and holds the button.  If the receiver gets an "raise volume up one unit", repeated at normal intervals, you get the behavior one would expect.

2020-11-25 01:41 UTC, ba58smith commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
Based on a conversation with @mairas , I've renamed DigitalInputValue to DigitalInputState. Is this a DigitalInputStateRepeater? (The more Sensors and Transforms we have, the harder it's going to be to name them.)

2020-11-25 01:42 UTC, ba58smith commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
I'm the one who's always arguing for making things as simple to understand as possible for end-users. So I retract my comment: I'm perfectly OK for a click and a double-click to do the same thing.

2020-11-25 01:45 UTC, ba58smith approved these changes
My comments have been addressed. Merge approved, once a better name is decided upon, and @mairas 's comments are addressed.

2020-11-25 08:10 UTC, mairas commented on src/transforms/click_type.h
> +enum class ClickTypes { SingleClick, LongSingleClick, UltraLongSingleClick, DoubleClick };
Yes, I would like to see events for both button press and release events (the transitions) and the semantic click, double click and long click events. It is then up to the observer to ignore the irrelevant ones and act accordingly.

2020-11-25 15:13 UTC, joelkoz commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
@ba58smith That sounds like a good candidate.  But to be clear - this class does not just repeat the state blindly.  It repeats the state ONLY IF it is "pressed" (be that HIGH or LOW).  If the digital input is in the opposite state, no repeating is done.  That is what makes this class different than say, the RepeatReport transform.

2020-11-25 15:21 UTC, joelkoz commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
@mairas Does `DigitalInputStateRepeater` work for you?

2020-11-25 17:20 UTC, ba58smith commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
OK, how about RepeaterOfTheDigitalPinStateIfTheButtonIsPressed? :-)

2020-11-25 17:35 UTC, mairas commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
> @mairas Does `DigitalInputStateRepeater` work for you?

Sure but I don't quite see what benefit you'd get over just using the RepeatReport transform from the other PR. Is it that you don't want to repeat the unpressed state? I'd rather have as few and as generic classes implementing digital input reading as possible and then using transforms to enriching the input in meaningful ways.

2020-11-25 17:42 UTC, joelkoz commented on src/sensors/button.h
> +class Button : public DigitalInput, public BooleanProducer {
@mairas That is EXACTLY the difference between the two.  The (currently named) Button only repeats is PRESSED state, and then only after it has been pressed for at least `repeat_start_interval`.  It is an entirely different thing from RepeatReport. It is why I think Button is actually appropriate, because this specialized behavior is unique (as far as I know) to buttons.  I don't mind making an intermediate transform that extracts out that behavior for use by other boolean producers, but I do think that a physical button, by far, is the most common use case. That is why if we do extract out this functionality, I still think we should have a high level `Button` class that combines the digital input and this repeater functionality.  Much easy for the hobbyist to use.

2020-11-27 23:36 UTC, joelkoz commented
Closing this PR and re-opening due to rebasing issues

2020-11-27 23:36 UTC, closed without merging