Sk output metadata support
SignalK/SensESP pull request #298
Opened 2020-12-05 16:41 UTC by joelkoz

This PR allows SensESP to send metadata describing the Signal K paths it is sending along with the first delta update it reports to the server.  Metadata is described in the Signal K specification here: https://signalk.org/specification/1.5.0/doc/data_model_metadata.html

Using this feature requires the Signal K Node Server version 1.37.3 or greater.

2020-12-06 20:57 UTC, mairas commented
This is an important addition, and at a quick look the PR would seem to be OK. I'd still want to read through it more carefully tomorrow.

2020-12-07 14:19 UTC, mairas requested changes
Overall very nice. Some minor comments. The `meta_sent_` lifecycle is the only thing that concerns me (assuming I got it right).

2020-12-07 14:19 UTC, mairas commented on src/signalk/signalk_delta.cpp
> +    : hostname{hostname}, max_buffer_size{max_buffer_size}, meta_sent_{false} {}
About the `meta_sent_` handling: didn't the new spec say the metadata should be sent once per connection? If the server is rebooted or the websocket gets disconnected for any other reason, I think `meta_sent_` should be cleared.

2020-12-07 14:19 UTC, mairas commented on src/signalk/signalk_emitter.h
> +  struct Metadata {
What was your reasoning for defining this inside SKEmitter? Given that it's an object instantiated by the end user, it'd feel more natural for me to have it in the global namespace. (Of course, we could debate whether we should start using namespaces for real, but maybe another time...)

2020-12-07 14:19 UTC, mairas commented on src/signalk/signalk_emitter.cpp
> +      JsonObject json = meta.createNestedObject();
Minor detail: should Metadata know how to serialize itself as a Json object?

2020-12-07 17:23 UTC, joelkoz commented on src/signalk/signalk_delta.cpp
> +    : hostname{hostname}, max_buffer_size{max_buffer_size}, meta_sent_{false} {}
I don't think the spec said anything official - they just didn't want it to be sent with each delta.  I agree however - if we lose the connection and re-connect, that could very well be because the server rebooted.  I'll expose this via a method, and then have ws_client modify it.  Unless ws_client can be subscribed to, in which case I'll do it the "right way."

2020-12-07 17:26 UTC, mairas commented on src/signalk/signalk_delta.cpp
> +    : hostname{hostname}, max_buffer_size{max_buffer_size}, meta_sent_{false} {}
Hmm, subscribing to it is indeed possible! I implemented the interface for status displays etc but the status led blinker uses it as well. And now that I remember, I'll create an issue to rename the interface classes to something more specific.

2020-12-07 17:28 UTC, mairas commented on src/signalk/signalk_delta.cpp
> +    : hostname{hostname}, max_buffer_size{max_buffer_size}, meta_sent_{false} {}
Correcting myself, LedBlinker et al are OK (in my opinion) but LedController should be StatusLedController or something like that.

2020-12-07 17:29 UTC, joelkoz commented on src/signalk/signalk_emitter.h
> +  struct Metadata {
I've always put data structures that are subordinate to classes inside those classes, especially when the name is generic.  On the other hand, when I went to actually use this in an app, SKEmitter seemed strange as its not a class an end user sees much if at all.  SKOutput would have been a more natural place.  And certainly it would be even easier if this were a global class. If so, I think it needs a prefix to act as a pseudo namespace, as simply "Metadata" is too generic I think.  Maybe `SKOutputMetadata`?  Or, we can stick with simply `Metadata`, as in practice, I don't think there is a huge risk of name collision.  The compromise is probably `SKMetadata`.  Ok with that?

2020-12-07 17:37 UTC, mairas commented on src/signalk/signalk_emitter.h
> +  struct Metadata {
SKMetadata or SKOutputMetadata, me thinks. It contains Signal K metadata, so I'd lean on SKMetadata.

2020-12-07 17:45 UTC, joelkoz commented on src/signalk/signalk_emitter.cpp
> +      JsonObject json = meta.createNestedObject();
The `Metadata` struct wasn't really intended to be the final word in serialization. As I mentioned in the comments, the `Metadata` struct is only a subset of the possible metadata that can be described.  I didn't think it was worth the effort to add support for things like Zones and alert methods as that stuff added complexity that I didn't think would be used much.  That meant we needed a way to extend it in the future. My goal was to have the "write the metadata" code be a `virtual` method that could be overwritten by any descendant of SKEmitter that needed the specialization, but there would be a simple implementation that would work in most cases. Now, I suppose we could instead make the default implementation be "ask Metadata to fill out the json", and any specialization would be done by overriding a `virtual` serialize method that is in `Metadata`.  The technique to extend the functionality would then be "create a descendant of Metadata and re-do the serialization class" vs. "make a custom version of SKOutput".  In theory that is going to add one more level of indirection as this method would just delegate to `Metadata`, but in practice, it's a negligible performance hit.  This approach makes even more sense if `Metadata` is made a global class.  Now that I've typed all this and seen the pieces laid out, I kind of like that approach better.  I'll do that.

2020-12-07 21:05 UTC, joelkoz commented on src/signalk/signalk_delta.cpp
> +    : hostname{hostname}, max_buffer_size{max_buffer_size}, meta_sent_{false} {}
After studying the code, it looks like SKDelta is co-owned by `SensESPApp` and `WSClient`, but SKDelta has no awareness of either. To minimize the number of changes, it was much simpler to expose a "reset meta send" method on SKDelta, and just have WSClient call that whenever it connected to an SK server. There were other options of course, but this was the quickest and safest.

2020-12-08 00:28 UTC, ba58smith commented on examples/analog_input.cpp
>    // and then output the results to the Signal K server.
Can you add to the comments immediately above? Something about what `new SKEmitter::Metadata("ratio")));` does.

2020-12-08 00:31 UTC, ba58smith approved these changes
Looks good to me! Just one small comment about a comment.

2020-12-08 14:41 UTC, joelkoz commented on examples/analog_input.cpp
>    // and then output the results to the Signal K server.
Sure.  FYI, "ratio" is the "units" field. It is the official name in the Signal K spec of a "ratio of one number to another" (aka a percentage represented as a number between 0.0 and 1.0)

2020-12-08 14:52 UTC, mairas commented
Looks good to me too. Could you clean the merge commits from the PR before merging? Something like
```
git checkout master
git pull upstream master
git checkout SKOutput-meta-data-support
git rebase master
# check the results before pushing
git log
git push -f origin SKOutput-meta-data-support
```
might clean them away.

The reason is that we're trying to keep the commit log clean to make it as readable and informative as possible.

2020-12-08 15:40 UTC, merged