Allow compilation when DEBUG_DISABLED defined
SignalK/SensESP pull request #359
Opened 2021-01-13 18:32 UTC by BjarneBitscrambler

Basically, we are unable to turn off the debug*() informative prints due to two small compilation errors. Corrected by including one #ifndef guard and one #include statement.  See #358 for details.

This resolves #358.

2021-01-13 18:40 UTC, BjarneBitscrambler commented
### Testing Performed
The changes compile and run on both ESP8266 (d1_mini) and ESP32 (WROVER).  

There are approx 8900 more bytes reported by freemem when running the smartswitch example on the d1_mini with DEBUG_DISABLED  (freemem = 22680 vs. 13768). And, with DEBUG_DISABLED, all is quiet on the serial port when running SensESP as expected.

2021-01-13 18:54 UTC, ba58smith requested changes

2021-01-13 18:54 UTC, ba58smith commented on src/sensesp_app.cpp
>    debugI("\nSerial debug enabled");
Shouldn't the debugI be above the #endif?

2021-01-13 19:02 UTC, ba58smith requested changes

2021-01-13 19:02 UTC, ba58smith commented on src/sensors/system_info.cpp
I'm not at my computer so I can't verify this: your change here fixes the situation if you disable debug. Does it cause a problem if you DON'T disable debug?

2021-01-13 19:45 UTC, BjarneBitscrambler commented on src/sensors/system_info.cpp
None that I've noticed.  Everything compiles, as evidenced by the auto-build checks (which I believe would be using the normal debug-enabled configuration). 
When I turn off debug msgs in RemoteDebug.*, I still see the expected info in the sensor's web interface, but the terminal window has zero traffic as it should. When debug msgs aren't disabled, the expected Signal K messages display in the terminal window.

2021-01-13 19:50 UTC, BjarneBitscrambler commented on src/sensesp_app.cpp
>    debugI("\nSerial debug enabled");
It could be, but it doesn't make any difference. The RemoteDebug library turns **all** debug_() calls into nothing (i.e. zero compiled code) when DEBUG_DISABLED is defined. So there's no need in any of the code to put #ifdef...#endif guards around the info messages.  That's why there's such a large savings in the code size.

2021-01-13 20:10 UTC, joelkoz approved these changes
These look OK to me.

2021-01-13 23:03 UTC, ba58smith commented on src/sensesp_app.cpp
>    debugI("\nSerial debug enabled");
I hadn't thought of that (that if debug is disabled, the debug message in question won't print). Just looks odd. But no need to change it.

2021-01-13 23:04 UTC, ba58smith approved these changes

2021-01-13 23:56 UTC, BjarneBitscrambler commented on src/sensesp_app.cpp
>    debugI("\nSerial debug enabled");
Great - thanks for reviewing!

2021-01-14 03:07 UTC, ba58smith commented
Closes #358 .

2021-01-14 03:07 UTC, merged